plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: pages-themes/modernist@v0.2.0
email: natan.saidon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Financial Technical Analysis
title: "Calusa Digital Solutions"

