theme: minima
email: natan.saidon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Financial Technical Analysis
title: "Calusa Digital Solutions"
plugins:
  - jekyll-feed
